import React from "react";
import "./Miningpool.css";
import miningpoolImg from "../assets/WhatsApp Image 2023-11-22 at 05.20.02_b7affb56.jpg";

const Miningpool = () => {
	return (
		<div className='miningpool-container'>
			<img src={miningpoolImg} alt={miningpoolImg} />
			<div className='miningpool-content'>
				<h2>About Our Mining Pool & How To Get Started</h2>
				<p>
					Join Our Mining Pool at HOMETRADE Elevate your Bitcoin mining
					experience by becoming a part of our collaborative mining pool. At
					HOMETRADE, we believe in the power of collective efforts, and our
					mining pool exemplifies this philosophy. What is a Mining Pool? A
					mining pool is a collective of miners who combine their computational
					resources to increase the likelihood of successfully mining a block.
					By pooling resources, miners share the rewards more consistently,
					providing a stable and predictable income stream. Why Choose
					HOMETRADE's Mining Pool? * Increased Profitability: Joining our mining
					pool enhances your chances of receiving regular and consistent
					rewards, providing a steady income stream. * Stability and
					Reliability: Benefit from the stability and reliability of our
					infrastructure, ensuring optimal mining performance. * Transparent
					Rewards: Our transparent reward distribution system ensures that each
					contributing miner receives a fair share of the rewards generated by
					the pool.
				</p>
				<div className='guildline'>
					<h3>How To Join</h3>
					<div className='steps'>
						<span>
							Create an Account: Sign up on our platform to create your mining
							account.
						</span>
						<span>
							Configure Your Miner: Set up your mining hardware to connect to
							our pool.
						</span>
						<span>
							Start Mining: Begin contributing your computational power to the
							pool and enjoy more predictable rewards.
						</span>
					</div>
					<p>
						Join us in reshaping the future of decentralized currency. Become a
						part of HOMETRADE's mining pool and unlock the true potential of
						collaborative mining.
					</p>
				</div>
			</div>
		</div>
	);
};

export default Miningpool;
